config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  get '/auth/:provider/callback', to: 'sessions#create'
# sessions
  get "/signin", to: "sessions#new"
  post "/sessions/create", to: "sessions#create"
  get "/signout", to: "sessions#destroy"

  post "/scholarships/new", to: "scholarships#new"


  resources :schools

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/scholarship.rb
class Scholarship < ActiveRecord::Base
  belongs_to :user
  belongs_to :school

  def offered_scholarship
    "You have been offered a scholarship!"
  end


  def offer_scholarship
    new_athletism = self.user.athletism + self.attraction.athletism_rating
    new_footwork = self.user.footwork + self.attraction.footwork_rating
    self.user.update(
      :athletism => new_athletism,
      :footwork => new_footwork
    )
    "Thanks for checking out our school #{self.school.name}!"
  end


end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :scholarships
  has_many :users, :through => :scholarships
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :scholarships
  has_many :schools, :through => :scholarships
  validates :email, :presence => true
  validates :email, :uniqueness => true

  def athletic
    if self.athletism && self.footwork
      athletic = self.athletism + self.footwork
      athletic > 5 ? "athletic" : "not athletic"
    end
  end

  def num_of_scholarships
    self.schools.count
  end

  def self.find_or_create_by_omniauth(auth_hash)
    self.where(:email => auth_hash["info"]["email"]).first_or_create do |user|
      user.password = SecureRandom.hex
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authentication_required
    if !logged_in?
      redirect_to root_path
    end
  end

  def logged_in?
    session[:user_id]
  end

  private
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user

end

app/controllers/scholarships_controller.rb
class ScholarshipsController < ApplicationController

  def new
    @scholarship = Scholarship.create(
      :user_id => params[:user_id],
      :school_id => params[:school_id]
    )
    @message = @scholarship.offered_scholarship
    redirect_to user_path(@scholarship.user, :message => @message)
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]
  before_action :authentication_required

  def index
    if session[:user_id].present?
      @schools = School.all
    else
      redirect_to root_path
    end
  end

  def show
    @scholarship = Scholarship.new
  end

  def new
    @school = School.new
  end

  def edit
  end

  def create
    @school = School.new(school_params)
    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.'}
      else
      format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
    end
  end

  private
    def set_school
      @school = School.find(params[:id])
    end

    def school_params
      params.require(:school).permit(
        :name,
        :min_sprint,
        :min_gpa,
        :athletism_rating,
        :footwork_rating
      )
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

  def new
    @user = User.new
    @users = User.all
  end

  def create
    if auth_hash = request.env["omniauth.auth"]
      @user = User.find_or_create_by_omniauth(auth_hash)
      session[:user_id] = @user.id
      
      redirect_to schools_path
    else
      @user = User.find_by(:email => params[:email])
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id

        redirect_to schools_url
      else
        render '/sessions/new'
      end
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
    @message = params[:message] if params[:message]
    @message ||= false
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    if @user.save
      session[:user_id] = @user.id
      redirect_to schools_path
    else
      render 'users/new'
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(
        :name,
        :email,
        :password,
        :height,
        :weight,
        :athletism,
        :footwork,
        :gpa,
        :admin
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScoutingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>

  <div class="field"> <%= f.label :name %><br>
  <%= f.text_field :name %></div>


  <div class="field"><%= f.label :athletism_rating, "How athletic are is your school? (1-5 scale)" %><br>
  <%= f.number_field :athletism_rating %></div>

  <div class="field"><%= f.label :footwork_rating, "How quick is your schools footwork? (1-5 scale)" %><br>
  <%= f.number_field :footwork_rating %></div>

  <div class="field"><%= f.label :min_gpa, "What is your minimum gpa to get into your school?" %><br>
  <%= f.number_field :min_gpa %></div>

  <div class="field"><%= f.label :min_sprint, "What is your minimum speed to get into your school?" %><br>
  <%= f.number_field :min_sprint %></div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<h1>Listing schools</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><strong>Name</strong></td>
      <td><strong>Minimum GPA</strong></td>
      <td><strong>Details</strong></td>
    </tr>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.name %></td>
        <td><%= school.min_gpa %></td>
        <% if current_user.admin %>
          <td><%= link_to "Show #{school.name}", school_path(school) %></td>
        <% else %>
          <td><%= link_to "Go to #{school.name}", school_path(school) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<% if @user %>
  <p>
    <%= link_to "Back to profile", user_path(@user), {:class => "btn btn-primary"} %>
  </p>
<% else %>
  <p><%= link_to 'New Schools', new_school_path %></p>
<% end %>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>
  <div class="info">
    <p><strong>Name:</strong> <%= @school.name %></p>
    <p><strong>Total Number of Users:</strong> <%= @school.users.count %></p>
    <p><strong>GPA Requirement:</strong> <%= @school.min_gpa %></p>
    <p><strong>Speed Requirement:</strong> <%= @school.min_sprint %> </p>
    <p><strong>Footwork Rating:</strong> <%= @school.footwork_rating %></p>
    <p><strong>Athletism Rating:</strong> <%= @school.athletism_rating %></p>
    <% if current_user.admin %>
      <%= link_to 'Edit School', [:edit, @school] %>
    <% else %>
      <form action="/scholarships/new" method="post">
        <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
        <%= tag(:input, :type => "hidden", :name => :user_id, :value => current_user.id) %>
        <%= tag(:input, :type => "hidden", :name => :attraction_id, :value => @school.id) %>
        <input type="submit" value="Go to this school">
      </form>
    <% end %>
    <%= link_to 'Back', schools_path %>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="scouting-showcase" role="main">

  <div class="left-pic">
    <img src="http://www.insideworldfootball.com/app/uploads/2017/01/Scouting.png" width="550" height="325">
  </div>

  <div class="right-info">
    <h1>Welcome to the Scouting App!</h1>
    <div class="center">
      <%= link_to "Sign in", signin_path %>
      <%= link_to "Sign up", new_user_path %>
    </div>
  </div>

</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field"> <%= f.label :name %><br>
  <%= f.text_field :name %></div>

  <div class="field"> <%= f.label :email %><br>
  <%= f.text_field :email %></div>

  <div class="field"> <%= f.label :password %><br>
  <%= f.text_field :password %></div>

  <div class="field"><%= f.label :height, "Height (in inches)" %><br>
  <%= f.number_field :height %></div>

  <div class="field"><%= f.label :weight, "Weight" %><br>
  <%= f.number_field :weight %></div>

  <div class="field"><%= f.label :athletism, "How athletic are you? (1-5 scale)" %><br>
  <%= f.number_field :athletism %></div>

  <div class="field"><%= f.label :footwork, "How good is your footwork? (1-5 scale)" %><br>
  <%= f.number_field :footwork %></div>

  <div class="field"><%= f.label :gpa, "What is your current GPA?" %><br>
  <%= f.number_field :gpa %></div>



  <div class="field">
    <%= f.label :admin, "Check box if you are the head scout?" %>
    <%= f.check_box :admin%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', schools_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>


<%= link_to 'Back', root_path %>

<%= link_to 'Login Via GitHub', "/auth/github" %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<% if @message %>
  <div class="center alert">
    <p><%= @message  %></p>
  </div>
<% end %>

  <div class="info">
    <% if @user.admin %>
      <p><strong>ADMIN</strong></p>
    <% end %>
    <p><strong>Name:</strong> <%= @user.name %></p>
    <p><strong>GPA:</strong> <%= @user.gpa %></p>
    <p><strong>Athletism:</strong>  <%= @user.athletism %></p>
    <p><strong>Footwork:</strong> <%= @user.footwork %> </p>
    <p><%= link_to 'Edit', edit_user_path(@user) %></p>
    <p><%= link_to 'See schools', schools_path %></p>
  </div>
</div>

app/views/users/signin.html.erb
<%= form_for @user, url: "/users/login" do |f| %>

  <div class="field"><%= f.label :name, "Select your name" %><br>
    <%= f.collection_select(:id, @users, :id, :name) %>
  </div>

  <div class="field"><%= f.label :password %><br>
  <%= f.text_field :password, :placeholder => "Enter your password!" %></div>

  <div class="actions">
    <%= f.submit "Sign In"  %>
  </div>
<% end %>